<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>BolivianDaily.CheckerWorker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BolivianDaily.CheckerWorker.Application\BolivianDaily.CheckerWorker.Application.csproj" />
    <ProjectReference Include="..\BolivianDaily.CheckerWorker.Infrastructure\BolivianDaily.CheckerWorker.Infrastructure.csproj" />
  </ItemGroup>

</Project>
