services:

  scraper-postgres:
    image: postgres:16
    container_name: scraper-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - scraper-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper_user -d scraper_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  checker-postgres:
    image: postgres:16
    container_name: checker-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: checker_db
      POSTGRES_USER: checker_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - checker-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checker_user -d checker_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  scraper-postgres-data:
  checker-postgres-data:
  rabbitmq-data:
