services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-scraper:
    image: postgres:16
    container_name: postgres-scraper
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-scraper-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scraper"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-checker:
    image: postgres:16
    container_name: postgres-checker
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-checker-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d checker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data:
  postgres-scraper-data:
  postgres-checker-data:
