// <auto-generated />
using System;
using BolivianDaily.CheckerWorker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BolivianDaily.CheckerWorker.Infrastructure.Migrations
{
    [DbContext(typeof(CheckerDbContext))]
    [Migration("20260809235139_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BolivianDaily.CheckerWorker.Domain.Entities.CheckedArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("CategoryAccuracyPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("category_accuracy_passed");

                    b.Property<string>("CategoryAccuracyReason")
                        .HasColumnType("text")
                        .HasColumnName("category_accuracy_reason");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DetectedNetworks")
                        .HasColumnType("text")
                        .HasColumnName("detected_networks");

                    b.Property<bool>("HtmlFormatPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("html_format_passed");

                    b.Property<string>("HtmlFormatReason")
                        .HasColumnType("text")
                        .HasColumnName("html_format_reason");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Lead")
                        .HasColumnType("text")
                        .HasColumnName("lead");

                    b.Property<bool>("NoAdvertisingPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("no_advertising_passed");

                    b.Property<string>("NoAdvertisingReason")
                        .HasColumnType("text")
                        .HasColumnName("no_advertising_reason");

                    b.Property<string>("Pretitle")
                        .HasColumnType("text")
                        .HasColumnName("pretitle");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("ReadyToPublishPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("ready_to_publish_passed");

                    b.Property<string>("ReadyToPublishReason")
                        .HasColumnType("text")
                        .HasColumnName("ready_to_publish_reason");

                    b.Property<long>("ScrapedArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("scraped_article_id");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_url");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("suggested_category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Warnings")
                        .HasColumnType("text")
                        .HasColumnName("warnings");

                    b.HasKey("Id");

                    b.HasIndex("ScrapedArticleId")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("checked_articles", (string)null);
                });

            modelBuilder.Entity("BolivianDaily.CheckerWorker.Domain.Entities.CheckedArticleMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CheckedArticleId")
                        .HasColumnType("bigint")
                        .HasColumnName("checked_article_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CheckedArticleId");

                    b.ToTable("checked_article_media", (string)null);
                });

            modelBuilder.Entity("BolivianDaily.CheckerWorker.Domain.Entities.CheckedArticleMedia", b =>
                {
                    b.HasOne("BolivianDaily.CheckerWorker.Domain.Entities.CheckedArticle", null)
                        .WithMany("Media")
                        .HasForeignKey("CheckedArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BolivianDaily.CheckerWorker.Domain.Entities.CheckedArticle", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
