CREATE TABLE processed_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scraped_article_id BIGINT NOT NULL,
    category_id BIGINT,
    source_id BIGINT,
    title VARCHAR(500) NOT NULL,
    pretitle VARCHAR(500),
    subtitle VARCHAR(500),
    enter TEXT,
    body TEXT NOT NULL,
    author VARCHAR(250),
    publication_date TIMESTAMP,
    state VARCHAR(1) NOT NULL DEFAULT 'A',
    processed_at TIMESTAMP NOT NULL,
    warnings TEXT,
    is_valid BOOLEAN NOT NULL DEFAULT FALSE,
    html_format_passed BOOLEAN NOT NULL DEFAULT FALSE,
    html_format_reason TEXT,
    category_accuracy_passed BOOLEAN NOT NULL DEFAULT FALSE,
    category_accuracy_reason TEXT,
    suggested_category VARCHAR(50),
    no_advertising_passed BOOLEAN NOT NULL DEFAULT FALSE,
    no_advertising_reason TEXT,
    detected_networks JSONB,
    ready_to_publish_passed BOOLEAN NOT NULL DEFAULT FALSE,
    ready_to_publish_reason TEXT,

    CONSTRAINT uq_processed_articles_scraped_article_id UNIQUE (scraped_article_id)
);

CREATE TABLE processed_article_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processed_article_id BIGINT NOT NULL,
    url VARCHAR(1000) NOT NULL,
    type VARCHAR(100) NOT NULL DEFAULT 'image/jpeg',
    description VARCHAR(500),
    path VARCHAR(1000),
    CONSTRAINT fk_processed_article_media_article
        FOREIGN KEY (processed_article_id)
        REFERENCES processed_articles(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_processed_article_media_article_id
    ON processed_article_media(processed_article_id);
