CREATE TABLE processed_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scraped_article_id BIGINT NOT NULL,
    source_id BIGINT,
    source_name VARCHAR(100) NOT NULL,
    source_url VARCHAR(255) NOT NULL,
    category_id BIGINT,
    category_name VARCHAR(100),
    article_url TEXT NOT NULL,
    title TEXT NOT NULL,
    pretitle TEXT,
    subtitle TEXT,
    enter TEXT,
    body TEXT NOT NULL,
    author VARCHAR(250),
    publication_date TIMESTAMP,
    scraped_at TIMESTAMP NOT NULL,
    state VARCHAR(1) NOT NULL DEFAULT 'A',
    processed_at TIMESTAMP NOT NULL,
    warnings TEXT,
    is_valid BOOLEAN NOT NULL DEFAULT FALSE,
    html_format_passed BOOLEAN NOT NULL DEFAULT FALSE,
    html_format_reason TEXT,
    category_accuracy_passed BOOLEAN NOT NULL DEFAULT FALSE,
    category_accuracy_reason TEXT,
    suggested_category VARCHAR(50),
    no_advertising_passed BOOLEAN NOT NULL DEFAULT FALSE,
    no_advertising_reason TEXT,
    detected_networks TEXT,
    ready_to_publish_passed BOOLEAN NOT NULL DEFAULT FALSE,
    ready_to_publish_reason TEXT,

    CONSTRAINT uq_processed_articles_scraped_article_id UNIQUE (scraped_article_id)
);

CREATE TABLE processed_article_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processed_article_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'image/jpeg',
    description TEXT,
    path VARCHAR(255),
    CONSTRAINT fk_processed_article_media_article
        FOREIGN KEY (processed_article_id)
        REFERENCES processed_articles(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_processed_article_media_article_id
    ON processed_article_media(processed_article_id);
