<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\BolivianDaily.Shared\BolivianDaily.Shared.csproj" />
    <ProjectReference Include="..\BolivianDaily.CheckerWorker.Application\BolivianDaily.CheckerWorker.Application.csproj" />
    <ProjectReference Include="..\BolivianDaily.CheckerWorker.Domain\BolivianDaily.CheckerWorker.Domain.csproj" />
  </ItemGroup>

</Project>
